defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: solarity
  username: jlizana
  password:

development: *defaults
production: *defaults
test: *defaults
