defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: solarity
  username: jlizana
  password:

production: *defaults
test: *defaults


development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000