# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f85a2efae8e5705c618ec6fa36da870b4e00f4c565285bc0d720ccb52bb6ea1959012bf36128cfcc527228387e5dd31e2daeaded6944599f049fd99892e6534b

test:
  secret_key_base: 4978ad6a8e659dcb6d7df9d393441e240e945b7519d49b370598fa3bcbbef4877df0f49d085835f3a8bbdc9a8bceccc989a2ef5ddebfd2b983315beee90593f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
